//! Modules module
//!
//! Built-in synthesizer modules.
//! Includes oscillators, filters, envelopes, LFOs, utilities, and output modules.

pub mod attenuverter;
pub mod audio_input;
pub mod chorus;
pub mod clock;
pub mod compressor;
pub mod delay;
pub mod divider;
pub mod distortion;
pub mod drum;
pub mod envelope;
pub mod eq;
pub mod filter;
pub mod keyboard;
pub mod ladder;
pub mod lfo;
pub mod logic;
pub mod looper;
pub mod midi_monitor;
pub mod mixer;
pub mod midi_note;
pub mod noise;
pub mod oscillator;
pub mod oscilloscope;
pub mod output;
pub mod poly_midi;
pub mod quantizer;
pub mod reverb;
pub mod sample_hold;
pub mod sampler;
pub mod sequencer;
pub mod trigger_sequencer;
pub mod vca;

// Re-export commonly used types
pub use attenuverter::Attenuverter;
pub use audio_input::AudioInput;
pub use chorus::Chorus;
pub use clock::Clock;
pub use compressor::Compressor;
pub use delay::StereoDelay;
pub use divider::ClockDivider;
pub use distortion::Distortion;
pub use drum::Drum;
pub use sampler::Sampler;
pub use envelope::AdsrEnvelope;
pub use eq::ParametricEq;
pub use filter::SvfFilter;
pub use keyboard::KeyboardInput;
pub use ladder::LadderFilter;
pub use lfo::Lfo;
pub use logic::Logic;
pub use looper::Looper;
pub use midi_monitor::MidiMonitor;
pub use mixer::Mixer;
pub use midi_note::MidiNote;
pub use noise::Noise;
pub use oscillator::Oscillator;
pub use oscilloscope::Oscilloscope;
pub use output::AudioOutput;
pub use poly_midi::PolyMidi;
pub use quantizer::Quantizer;
pub use reverb::Reverb;
pub use sample_hold::SampleHold;
pub use sequencer::StepSequencer;
pub use trigger_sequencer::TriggerSequencer;
pub use vca::Vca;
