//! Response types for node graph UI events.
//!
//! Defines the custom events that can be generated by node interactions.

use egui_node_graph2::UserResponseTrait;

/// Custom responses generated by node graph interactions.
///
/// These events are collected during UI drawing and processed
/// to trigger actions like syncing with the audio engine.
#[derive(Clone, Debug, PartialEq)]
pub enum SynthResponse {
    /// A parameter value was changed.
    ParameterChanged {
        node_id: egui_node_graph2::NodeId,
        param_name: String,
        value: f32,
    },
    /// Parameters set together by one gesture on a node's display, such as
    /// a click on the Trigger Sequencer's grid. Undo takes them back as one
    /// step of their own, named `label`, however quickly the next follows.
    EditParameters {
        node_id: egui_node_graph2::NodeId,
        label: String,
        changes: Vec<(String, f32)>,
    },
    /// A parameter played rather than edited, like a Looper's footswitch
    /// pressed on the node: it reaches the engine at once, as a MIDI
    /// controller's would, and isn't an undo step.
    PlayParameter {
        node_id: egui_node_graph2::NodeId,
        param_name: String,
        value: f32,
    },
    /// A node was selected by right-clicking it, so its menu acts on it.
    NodeSelected(egui_node_graph2::NodeId),
    /// A node was deselected.
    NodeDeselected(egui_node_graph2::NodeId),
    /// Request to delete a node.
    DeleteNode(egui_node_graph2::NodeId),
    /// Request to reset a node's parameters to defaults.
    ResetNode(egui_node_graph2::NodeId),
    /// Request to duplicate a node, with the cables between it and any
    /// other selected nodes.
    DuplicateNode(egui_node_graph2::NodeId),
    /// Request to copy a node to the clipboard.
    CopyNode(egui_node_graph2::NodeId),
    /// Request to bypass a node, or bring it back.
    ToggleBypass(egui_node_graph2::NodeId),
    /// Request to start MIDI Learn mode for a parameter.
    MidiLearnStart {
        engine_node_id: u64,
        param_index: usize,
        param_name: String,
        min_value: f32,
        max_value: f32,
    },
    /// Request to clear MIDI mapping for a parameter.
    MidiLearnClear {
        engine_node_id: u64,
        param_index: usize,
    },
    /// Request to leave MIDI Learn mode without mapping anything.
    MidiLearnCancel,
    /// Show a module's knob on the faces of the groups around it, `levels`
    /// groups up (0 takes it off them all).
    PinKnob {
        node_id: egui_node_graph2::NodeId,
        param_name: String,
        levels: u8,
    },
    /// Show a port on the group it's in as a new jack, unplug it from the
    /// group's jack, or take away the jack it is.
    Jack {
        node_id: egui_node_graph2::NodeId,
        side: super::groups::Side,
        port: String,
        action: super::groups::JackAction,
    },
    /// Group the selection the node is part of (or just the node).
    GroupNode(egui_node_graph2::NodeId),
    /// Take a group apart onto the level it sits on.
    UngroupNode(egui_node_graph2::NodeId),
    /// Show the inside of a group.
    EnterGroup(egui_node_graph2::NodeId),
    /// Start typing a group's name.
    StartRename(egui_node_graph2::NodeId),
    /// A group's new name, typed.
    RenameGroup {
        node_id: egui_node_graph2::NodeId,
        name: String,
    },
    /// Save a group to My Modules.
    SaveGroup(egui_node_graph2::NodeId),
    /// Ask for a file for a Sampler to play.
    OpenSample(egui_node_graph2::NodeId),
}

impl SynthResponse {
    /// Create a parameter changed response.
    pub fn parameter_changed(
        node_id: egui_node_graph2::NodeId,
        param_name: impl Into<String>,
        value: f32,
    ) -> Self {
        Self::ParameterChanged {
            node_id,
            param_name: param_name.into(),
            value,
        }
    }

    /// Create a node selected response.
    pub fn node_selected(node_id: egui_node_graph2::NodeId) -> Self {
        Self::NodeSelected(node_id)
    }

    /// Create a node deselected response.
    pub fn node_deselected(node_id: egui_node_graph2::NodeId) -> Self {
        Self::NodeDeselected(node_id)
    }

    /// Create a delete node response.
    pub fn delete_node(node_id: egui_node_graph2::NodeId) -> Self {
        Self::DeleteNode(node_id)
    }

    /// Create a reset node response.
    pub fn reset_node(node_id: egui_node_graph2::NodeId) -> Self {
        Self::ResetNode(node_id)
    }

    /// Create a MIDI learn start response.
    pub fn midi_learn_start(
        engine_node_id: u64,
        param_index: usize,
        param_name: impl Into<String>,
        min_value: f32,
        max_value: f32,
    ) -> Self {
        Self::MidiLearnStart {
            engine_node_id,
            param_index,
            param_name: param_name.into(),
            min_value,
            max_value,
        }
    }

    /// Create a MIDI learn clear response.
    pub fn midi_learn_clear(engine_node_id: u64, param_index: usize) -> Self {
        Self::MidiLearnClear {
            engine_node_id,
            param_index,
        }
    }
}

impl UserResponseTrait for SynthResponse {}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_node_id() -> egui_node_graph2::NodeId {
        // Create a test node ID (egui_node_graph2 uses slotmap internally)
        // We'll use a workaround since NodeId is opaque
        unsafe { std::mem::transmute(1u64) }
    }

    #[test]
    fn test_parameter_changed() {
        let node_id = make_node_id();
        let response = SynthResponse::parameter_changed(node_id, "frequency", 440.0);

        match response {
            SynthResponse::ParameterChanged {
                param_name, value, ..
            } => {
                assert_eq!(param_name, "frequency");
                assert!((value - 440.0).abs() < f32::EPSILON);
            }
            _ => panic!("Expected ParameterChanged"),
        }
    }

    #[test]
    fn test_node_selected() {
        let node_id = make_node_id();
        let response = SynthResponse::node_selected(node_id);

        assert!(matches!(response, SynthResponse::NodeSelected(_)));
    }

    #[test]
    fn test_delete_node() {
        let node_id = make_node_id();
        let response = SynthResponse::delete_node(node_id);

        assert!(matches!(response, SynthResponse::DeleteNode(_)));
    }

    #[test]
    fn test_response_clone() {
        let node_id = make_node_id();
        let original = SynthResponse::parameter_changed(node_id, "test", 1.0);
        let cloned = original.clone();

        assert_eq!(original, cloned);
    }
}
