//! Response types for node graph UI events.
//!
//! Defines the custom events that can be generated by node interactions.

use egui_node_graph2::UserResponseTrait;

/// Custom responses generated by node graph interactions.
///
/// These events are collected during UI drawing and processed
/// to trigger actions like syncing with the audio engine.
#[derive(Clone, Debug, PartialEq)]
pub enum SynthResponse {
    /// A parameter value was changed.
    ParameterChanged {
        node_id: egui_node_graph2::NodeId,
        param_name: String,
        value: f32,
    },
    /// A node was selected.
    NodeSelected(egui_node_graph2::NodeId),
    /// A node was deselected.
    NodeDeselected(egui_node_graph2::NodeId),
    /// Request to delete a node.
    DeleteNode(egui_node_graph2::NodeId),
    /// Request to reset a node's parameters to defaults.
    ResetNode(egui_node_graph2::NodeId),
}

impl SynthResponse {
    /// Create a parameter changed response.
    pub fn parameter_changed(
        node_id: egui_node_graph2::NodeId,
        param_name: impl Into<String>,
        value: f32,
    ) -> Self {
        Self::ParameterChanged {
            node_id,
            param_name: param_name.into(),
            value,
        }
    }

    /// Create a node selected response.
    pub fn node_selected(node_id: egui_node_graph2::NodeId) -> Self {
        Self::NodeSelected(node_id)
    }

    /// Create a node deselected response.
    pub fn node_deselected(node_id: egui_node_graph2::NodeId) -> Self {
        Self::NodeDeselected(node_id)
    }

    /// Create a delete node response.
    pub fn delete_node(node_id: egui_node_graph2::NodeId) -> Self {
        Self::DeleteNode(node_id)
    }

    /// Create a reset node response.
    pub fn reset_node(node_id: egui_node_graph2::NodeId) -> Self {
        Self::ResetNode(node_id)
    }
}

impl UserResponseTrait for SynthResponse {}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_node_id() -> egui_node_graph2::NodeId {
        // Create a test node ID (egui_node_graph2 uses slotmap internally)
        // We'll use a workaround since NodeId is opaque
        unsafe { std::mem::transmute(1u64) }
    }

    #[test]
    fn test_parameter_changed() {
        let node_id = make_node_id();
        let response = SynthResponse::parameter_changed(node_id, "frequency", 440.0);

        match response {
            SynthResponse::ParameterChanged {
                param_name, value, ..
            } => {
                assert_eq!(param_name, "frequency");
                assert!((value - 440.0).abs() < f32::EPSILON);
            }
            _ => panic!("Expected ParameterChanged"),
        }
    }

    #[test]
    fn test_node_selected() {
        let node_id = make_node_id();
        let response = SynthResponse::node_selected(node_id);

        assert!(matches!(response, SynthResponse::NodeSelected(_)));
    }

    #[test]
    fn test_delete_node() {
        let node_id = make_node_id();
        let response = SynthResponse::delete_node(node_id);

        assert!(matches!(response, SynthResponse::DeleteNode(_)));
    }

    #[test]
    fn test_response_clone() {
        let node_id = make_node_id();
        let original = SynthResponse::parameter_changed(node_id, "test", 1.0);
        let cloned = original.clone();

        assert_eq!(original, cloned);
    }
}
